/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoKardex, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //11-05-2026  3. Implementacion Marca y Linea
                              
package Vista.Logistica;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author macoh
 */
public class frmMantenimientoKardex extends javax.swing.JInternalFrame {
    private javax.swing.table.DefaultTableModel modeloKardex;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoKardex.class.getName());

    /**
     * Creates new form frmMantenimientoKardex
     */
    public frmMantenimientoKardex() {
      initComponents();
    cargarPermisos(); 

    modeloKardex = new javax.swing.table.DefaultTableModel(
        new Object [][] {}, 
        new String [] { "ID Movimiento", "Tipo de Movimiento", "Producto", "Fecha", "Cantidad", "Marca", "Linea" }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Nadie edita manualmente
        }
    };
    tablaKardex.setModel(modeloKardex);
    cargarDatosEjemplo();
    this.setClosable(true);
    this.setIconifiable(true);
    this.setMaximizable(true);
    this.setResizable(true);
}
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2001 es el código de la aplicación Mantenimiento Kardex
        int codigoAplicacion = 2001; 

        // Como es un Kardex, por ahora solo validamos el botón Buscar
     //   btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
        btnBuscar.setEnabled(true); // Para consulta 
        
        /* 
        Si más adelante agregas más botones a este formulario, puedes usar esto:
        btnRegistrar.setEnabled(permisosDAO.puedeInsertar(usuId, codigoAplicacion));
        btnModificar.setEnabled(permisosDAO.puedeModificar(usuId, codigoAplicacion));
        btnEliminar.setEnabled(permisosDAO.puedeEliminar(usuId, codigoAplicacion));
        btnReportes.setEnabled(permisosDAO.puedeReportar(usuId, codigoAplicacion));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaKardex = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Movimiento", "Tipo de Movimiento", "Producto", "Fecha", "Cantidad", "Marca", "Linea"
            }
        ));
        tablaKardex.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaKardexAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaKardex);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Kardex Bodega");

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Movimiento", "Tipo de Movimiento", "Producto", "Fecha", "Marca", "Linea" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 49, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(btnBuscar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 49, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAyuda))
                .addContainerGap(478, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(18, 18, 18)
                    .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(101, 101, 101)
                    .addComponent(btnBuscar)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBuscar.setText("");
    tablaKardex.clearSelection();
    cboxTipoBusqueda.setSelectedIndex(0);
        cargarPermisos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tablaKardexAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaKardexAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaKardexAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
 
    txtBuscar.setText("");
    txtBuscar.requestFocus();
    String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
    switch (seleccion) {
        case "ID Movimiento":
            buscarPorIDk();
            break;
        case "Tipo de Movimiento":
            buscarPorMovimiento();
            break;
        case "Producto":
            buscarPorProducto();
            break;
        case "Fecha":
            buscarPorFechak();
            break;
         case "Marca":
             buscarPorMarca();
            break;
        case "Linea":
            buscarPorLinea(); 
            break; 
    }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String filtro = txtBuscar.getText().trim().toLowerCase();
    String criterio = cboxTipoBusqueda.getSelectedItem().toString();
    boolean encontrado = false;

    if (filtro.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar.");
        return;
    }
    int columna = 0;
    if (criterio.equals("ID Movimiento")) columna = 0;
    else if (criterio.equals("Tipo de Movimiento")) columna = 1;
    else if (criterio.equals("Producto")) columna = 2;
    else if (criterio.equals("Fecha")) columna = 3;


    for (int i = 0; i < tablaKardex.getRowCount(); i++) {
        String valorCelda = tablaKardex.getValueAt(i, columna).toString().toLowerCase();
        
        if (valorCelda.contains(filtro)) {
            tablaKardex.setRowSelectionInterval(i, i);
            encontrado = true;
            break; 
        }
    }

    if (!encontrado) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró coincidencia para: " + filtro);
    }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String filtro = txtBuscar.getText().trim();
    String criterio = cboxTipoBusqueda.getSelectedItem().toString();

    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tablaKardex.getModel());
    tablaKardex.setRowSorter(sorter);

    if (filtro.length() == 0) {
        sorter.setRowFilter(null);
    } else {
        int indiceColumna = 0;
switch (criterio) {
    case "ID Movimiento": 
        indiceColumna = 0; 
        break;
    case "Tipo de Movimiento":
        indiceColumna = 1; 
        break;
    case "Producto": 
        indiceColumna = 2; 
        break;
    case "Fecha":
        indiceColumna = 3; 
        break;
    case "Marca":
        indiceColumna = 5;
        break;
     case "Linea": 
         indiceColumna = 6;
         break;
    
    default:
        indiceColumna = 0;
        break;
}

        try {

            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, indiceColumna));
            if (tablaKardex.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
            }
        } catch (Exception e) {
            System.err.println("Error en el filtro: " + e.getMessage());
        }
    }
        //Registro de la accion en bitacora
        //     BitacoraDAO bitacoraDAO = new BitacoraDAO();
        //    bitacoraDAO.insert(idUsuario, Aplcodigo, "CONSULTA");    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAyudaActionPerformed
private void buscarPorIDk() {
        System.out.println("Buscando por ID en la BD...");
    }

    private void buscarPorMovimiento() {
        System.out.println("Buscando por Tipo (Entrada/Salida)...");
    }

    private void buscarPorProducto() {
        System.out.println("Buscando por nombre de Producto...");
    }

    private void buscarPorFechak() {
        System.out.println("Buscando por Fecha...");
    }
     private void buscarPorMarca() {
        System.out.println("Buscando por Marca...");
    }
      private void buscarPorLinea() {
        System.out.println("Buscando por Linea...");
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoKardex().setVisible(true));
    }

private void cargarDatosEjemplo() {
  modeloKardex.addRow(new Object[]{"101", "Entrada", "Martillo", "24/04/2026", "50", "Truper", "Ferretería"});
    modeloKardex.addRow(new Object[]{"102", "Salida", "Clavos", "25/04/2026", "200", "Standley", "Construcción"});
}

public void registrarMovimientoExterno(Object[] fila) {
    if (fila.length == 7) {
        modeloKardex.addRow(fila);
    } else {
        System.out.println("Error: El movimiento no tiene las 7 columnas requeridas.");
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaKardex;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
