/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoTransporte, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones


package Vista.Logistica;

import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import Controlador.Logistica.clsTransportistas;
import Modelo.Logistica.TransportistasDAO;
import java.io.File;

/**
 *
 * @author macoh
 */
public class frmMantenimientoTransporte extends javax.swing.JInternalFrame {
private DefaultTableModel modeloTransportes;

    public frmMantenimientoTransporte() {
        // 1. PRIMERO: NetBeans construye los botones, textos y tablas
        initComponents();
        
        // 2. SEGUNDO: Configuramos nuestra tabla manual
        modeloTransportes = new DefaultTableModel(new Object[]{"ID", "Nombre", "Tipo de Vehículo"}, 0);
        tablaTransporte.setModel(modeloTransportes);
        
        // 3. TERCERO: Cargamos datos existentes y permisos
        actualizarTabla();
        cargarPermisos();
        
        cargarDatosPrueba();

        // Configuración de la ventana
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
    }
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2000 es el código de la aplicación Mantenimiento Transportes
        int codigoAplicacion = 2000; 

        // Validamos únicamente el botón de Buscar
        btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTransporte = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        label19 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        txtIngresarVehiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 736));
        getContentPane().setLayout(null);

        tablaTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo de Vehiculo"
            }
        ));
        tablaTransporte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaTransporteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaTransporte);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 270, 692, 406);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Transportes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(264, 23, 107, 25);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(190, 170, 77, 27);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(100, 200, 90, 27);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(20, 170, 80, 27);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(170, 80, 76, 27);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes);
        btnReportes.setBounds(20, 200, 80, 27);

        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(190, 200, 76, 27);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(100, 170, 85, 27);

        label19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label19.setText("ID a buscar");
        getContentPane().add(label19);
        label19.setBounds(20, 80, 66, 16);
        getContentPane().add(txtbuscado);
        txtbuscado.setBounds(100, 80, 68, 26);

        label15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label15.setText("Ingresar Vehiculo");
        getContentPane().add(label15);
        label15.setBounds(20, 130, 103, 16);

        txtIngresarVehiculo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIngresarVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIngresarVehiculo);
        txtIngresarVehiculo.setBounds(140, 130, 120, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTransporteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaTransporteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTransporteAncestorAdded

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    
    if (!txtbuscado.getText().trim().isEmpty()) {
        int id = Integer.parseInt(txtbuscado.getText().trim());
        if (transporteDAO.eliminar(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Eliminado con éxito");
            actualizarTabla();
            btnLimpiarActionPerformed(null); // Limpia los campos
        }
    }
    
    if (!txtbuscado.getText().trim().isEmpty()) {
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este transportista?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (respuesta == 0) { // 0 es YES
            int id = Integer.parseInt(txtbuscado.getText().trim());
            if (transporteDAO.eliminar(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Registro eliminado.");
                actualizarTabla();
                btnLimpiarActionPerformed(null);
            }
        }
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

   txtbuscado.setText("");
    txtIngresarVehiculo.setText("");
    txtbuscado.requestFocus();
 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
Controlador.Logistica.clsTransportistas transporte = new Controlador.Logistica.clsTransportistas();
    Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();

    // VALIDACIÓN: No permitir campos vacíos
    if (txtIngresarVehiculo.getText().trim().isEmpty() || txtbuscado.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el vehículo y el ID del empleado.");
        return;
    }

    try {
        // CAPTURA: Pasamos los datos de la Vista al Objeto
        transporte.setTrantipovehiculo(txtIngresarVehiculo.getText().trim());
        
        // El ID del empleado lo tomamos de 'txtbuscado'
        int idEmp = Integer.parseInt(txtbuscado.getText().trim());
        transporte.setEmpcodigo(idEmp);

        // ACCIÓN: Llamamos al DAO para que inserte en la base de datos
       boolean respuesta = transporteDAO.insertar(transporte);

if (respuesta) { // Si es true, el registro fue exitoso
    javax.swing.JOptionPane.showMessageDialog(this, "¡Éxito! Transporte registrado correctamente.");
    actualizarTabla(); 
    
    // Limpiamos los campos
    txtIngresarVehiculo.setText("");
    txtbuscado.setText("");
    txtIngresarVehiculo.requestFocus();
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: El registro no se pudo guardar.");
}

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El ID del empleado debe ser un número entero.");
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      
Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    Controlador.Logistica.clsTransportistas transporteConsultado;
    
    try {
        int idBuscar = Integer.parseInt(txtbuscado.getText().trim());
        
        // 2. LLAMAR AL MÉTODO DESDE EL OBJETO 'transporteDAO'
        transporteConsultado = transporteDAO.buscarPorId(idBuscar);

        if (transporteConsultado != null) {
            txtIngresarVehiculo.setText(transporteConsultado.getTrantipovehiculo());
            javax.swing.JOptionPane.showMessageDialog(this, "Registro encontrado.");
        } else {
            // Si entra aquí, es porque el DAO no encontró el ID en la base de datos real
            javax.swing.JOptionPane.showMessageDialog(this, "El ID no está registrado en la Base de Datos.");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
    
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
   Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    Controlador.Logistica.clsTransportistas transporte = new Controlador.Logistica.clsTransportistas();

    try {
        // Usamos el ID que se cargó en txtbuscado al hacer clic en la tabla
        transporte.setTranid(Integer.parseInt(txtbuscado.getText().trim()));
        transporte.setTrantipovehiculo(txtIngresarVehiculo.getText().trim());
        
        if (transporteDAO.actualizar(transporte)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Modificado con éxito");
            actualizarTabla(); // Para ver el cambio reflejado
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
    }

    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoTransporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoTransporte().setVisible(true));
    }
    
    
    private void buscarPorID() {
        System.out.println("Buscando por ID...");
      
    }

    private void buscarPorNombre() {
        System.out.println("Buscando por Nombre...");
    }

    private void buscarPorEmpresa() {
        System.out.println("Buscando por Empresa...");
    }

    private void buscarPorTipo() {
        System.out.println("Buscando por Tipo de Vehículo...");
    }
    
    
   public void actualizarTabla() {
    Modelo.Logistica.TransportistasDAO transporteDAO = new Modelo.Logistica.TransportistasDAO();
    // Usamos el nombre exacto de tu DAO: listar()
    List<Controlador.Logistica.clsTransportistas> lista = transporteDAO.listar();

    modeloTransportes.setRowCount(0); 

    for (Controlador.Logistica.clsTransportistas t : lista) {
        modeloTransportes.addRow(new Object[]{
            t.getTranid(),            // Coincide con tu controlador
            "Empleado " + t.getEmpcodigo(), 
            t.getTrantipovehiculo()   // Coincide con tu controlador
        });
    }
}
   
   private void cargarDatosPrueba() {
    // Simulamos que el sistema "jaló" estos 3 choferes de la base de datos
    modeloTransportes.addRow(new Object[]{"1", "Marco Hernandez", "Camión de Carga"});
    modeloTransportes.addRow(new Object[]{"2", "Juan Pérez", "Panel Reparto"});
    modeloTransportes.addRow(new Object[]{"3", "Luis Gómez", "Motocicleta"});
}
   
   private void tablaTransporteMouseClicked(java.awt.event.MouseEvent evt) {                                             
    // 1. Identificar qué fila se tocó
    int filaSeleccionada = tablaTransporte.getSelectedRow();
    
    // 2. Si hay una fila seleccionada, extraer los datos
    if (filaSeleccionada != -1) {
        // Obtenemos el ID (Columna 0) y lo pasamos al cuadro de texto
        String id = tablaTransporte.getValueAt(filaSeleccionada, 0).toString();
        String vehiculo = tablaTransporte.getValueAt(filaSeleccionada, 2).toString();
        
        txtbuscado.setText(id);
        txtIngresarVehiculo.setText(vehiculo);
        
        // Opcional: Mandar un mensaje a la consola para confirmar
        System.out.println("Seleccionado ID: " + id);
    }
}
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label19;
    private javax.swing.JTable tablaTransporte;
    private javax.swing.JTextField txtIngresarVehiculo;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
