/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientStock, implementaciones basicas
                              //09-05-2026  2. Implementacion de funcionalidad de botones
                              //11-05-2026  3. Implementacion Marca y Linea
package Vista.Logistica;
import Controlador.clsUsuarioConectado;
import Modelo.PermisosDAO;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.util.List;

/**
 *
 * @author macoh
 */
public class frmMantenimientoStock extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoStock.class.getName());
private DefaultTableModel modeloStock;
    /**
     * Creates new form frmMantenimientoStock
     */
public frmMantenimientoStock() {
        initComponents();
        cargarPermisos(); 
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        
        modeloStock = (DefaultTableModel) tablaStock.getModel();
        tablaStock.setDefaultEditor(Object.class, null);
  
        cargarDatosPrueba();
    }

    private void cargarDatosPrueba() {
      modeloStock.addRow(new Object[]{"101", "Martillo", "50", "Unidades", "Truper", "Ferretería"});
    modeloStock.addRow(new Object[]{"102", "Clavos 2 pulg", "200", "Bolsas", "Standley", "Construcción"});
    modeloStock.addRow(new Object[]{"103", "Pintura Látex", "15", "Cubetas", "Sherwin", "Pinturas"});
    };

  
 
    public void cargarPermisos() {
        // Obtener el ID del usuario conectado
        int usuId = clsUsuarioConectado.getUsuId();
        PermisosDAO permisosDAO = new PermisosDAO();

        // 2002 es el código de la aplicación Mantenimiento Stock
        int codigoAplicacion = 2002; 

        // Validamos únicamente el botón de Buscar
        btnBuscar.setEnabled(permisosDAO.puedeBuscar(usuId, codigoAplicacion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAdyda = new javax.swing.JButton();

        jButton3.setText("Ayuda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Nombrer", "Stock Actual", "Existencias", "Marca", "Linea"
            }
        ));
        tablaStock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaStockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaStock);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Stock");

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Producto", "Nombre", "Marca", "Linea" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAdyda.setText("Ayuda");
        btnAdyda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdydaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdyda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 226, Short.MAX_VALUE)
                    .addComponent(btnBuscar)
                    .addGap(0, 435, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnAdyda))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 216, Short.MAX_VALUE)
                    .addComponent(btnBuscar)
                    .addGap(0, 449, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
     txtBuscar.setText("");
        cboxTipoBusqueda.setSelectedIndex(0);
        if (tablaStock.getRowSorter() != null) {
            tablaStock.setRowSorter(null); // Quita filtros
        }
        cargarDatosPrueba();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tablaStockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaStockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaStockAncestorAdded

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
        // TODO add your handling code here:

        // Oculta todos los campos de búsqueda al inicio
        // para evitar que aparezcan controles innecesarios
        /*    txtBuscar.setVisible(false);
        fechaInicio.setVisible(false);
        fechaFin.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnBuscar.setVisible(false);
        */
        // Obtiene el tipo de búsqueda seleccionado en el ComboBox
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();

        // Dependiendo del tipo de búsqueda se muestran
        // los controles necesarios para ingresar los datos
        switch (seleccion) {
            case "ID":
            buscarPorIDS();
            break;
            case "Nombre":
            buscarPorNombreS();
            break;
           case "Marca":
             buscarPorMarca();
            break;
        case "Linea":
            buscarPorLinea(); 
            break; 
        }
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        
       String filtro = txtBuscar.getText().trim();
    if (filtro.isEmpty()) {
        return;
    }

    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloStock);
    tablaStock.setRowSorter(sorter);
    
    String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
    int columnaIndex = 0;

    // Asignación de índices según las columnas de la tabla
    switch (seleccion) {
        case "ID Producto": columnaIndex = 0; break;
        case "Nombre":      columnaIndex = 1; break;
        case "Marca":       columnaIndex = 4; break;
        case "Linea":       columnaIndex = 5; break;
    }

    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     String filtro = txtBuscar.getText().trim();
    
    if (filtro.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Creamos el sorter para la tabla
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modeloStock);
    tablaStock.setRowSorter(sorter);

    String seleccion = cboxTipoBusqueda.getSelectedItem().toString();
    int columnaIndex = 0;

    // Determinamos el índice de la columna según lo seleccionado
    switch (seleccion) {
        case "ID Producto": columnaIndex = 0; break;
        case "Nombre":      columnaIndex = 1; break;
        case "Marca":       columnaIndex = 4; break;
        case "Linea":       columnaIndex = 5; break;
        default: columnaIndex = 0; break;
    }

    // Aplicamos el filtro (insensible a mayúsculas/minúsculas)
    try {
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + filtro, columnaIndex));
        
        // Si no hay resultados, avisamos al usuario
        if (tablaStock.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron coincidencias.");
        }
    } catch (Exception e) {
        System.err.println("Error en filtro: " + e.getMessage());
    }
        //Registro de la accion en bitacora
        //     BitacoraDAO bitacoraDAO = new BitacoraDAO();
        //    bitacoraDAO.insert(idUsuario, Aplcodigo, "CONSULTA");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAdydaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdydaActionPerformed
         Vista.Logistica.frmAyuda ventanaAyuda = new Vista.Logistica.frmAyuda();
    
    ventanaAyuda.setVisible(true);
    ventanaAyuda.setLocationRelativeTo(null);
    
    //Ferdynand Monroy mayo 2026: agregue la ayuda junto al archivo .chm
        
        try {
        String ruta = "C:\\Users\\ferit\\Desktop\\proyectop32k26b\\proyectop32k26b\\src\\main\\java\\Ayudas\\Logistica\\Logistica.chm";

        File archivo = new File(ruta);

        if (archivo.exists()) {
            Runtime.getRuntime().exec(
                "rundll32 url.dll,FileProtocolHandler \"" + ruta + "\""
            );
        } else {
            System.out.println("La ayuda no fue encontrada");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAdydaActionPerformed
private void buscarPorIDS() {
        System.out.println("Buscando por ID en la BD...");
    }
private void buscarPorMarca() {
    System.out.println("Buscando por Marca en Stock...");
}

private void buscarPorLinea() {
    System.out.println("Buscando por Línea en Stock...");
}

    private void buscarPorNombreS() {
        System.out.println("Buscando por Tipo (Entrada/Salida)...");
    }

  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoStock().setVisible(true));
    }
    
    
    private void cargarDatosEjemplo() {
    modeloStock.addRow(new Object[]{"P001", "Martillo Pro", "50", "Unidades"});
    modeloStock.addRow(new Object[]{"P002", "Clavos 2 pulg", "500", "Bolsas"});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdyda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
